services:
  db:
    image: mysql:8.0.44
    container_name: boostus_db
    restart: unless-stopped
    #실제 db의 환경변수는 docker file에 명시될 필요가 없다.
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=boostus
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    #개발 단계에서 db 접속을 위해 포트를 노출한다.
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - boostus_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ptest"]
      interval: 5s
      timeout: 3s
      retries: 20
  backend:
    image: node:24.11.0-alpine
    container_name: boostus_backend
    working_dir: /app
    volumes:
      - ./BE:/app
      - /app/node_modules
    command: sh -c "npm install && npm run prisma:generate && npm run start:dev"
    #be는 api 테스트를 위햐서 개발 단계에서는 외부에 포트가 열려있어야한다.
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=test
      - DB_NAME=boostus
      - NODE_ENV=development
      - JWT_SECRET=secret
      - JWT_ACCESS_EXPIRES_IN=3600
      - JWT_REFRESH_EXPIRES_IN=604800
      - FRONTEND_URL=http://localhost:5173
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - boostus_network

  frontend:
    image: node:24.11.0-alpine
    container_name: boostus_frontend
    working_dir: /app
    volumes:
      - ./FE:/app
      - /app/node_modules
    command: sh -c "corepack enable && pnpm install && pnpm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - boostus_network
    environment:
      - INTERNAL_API_URL=http://backend:3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NODE_ENV=development

  crawler:
    image: node:24.11.0-alpine
    container_name: boostus_crawler
    working_dir: /app
    volumes:
      - ./Crawler:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5000:5000"

  redis:
    image: redis:7-alpine
    container_name: boostus_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - boostus_network

networks:
  boostus_network:
    driver: bridge
volumes:
  db_data:
