name: be-ci

on:
  pull_request:
    branches: [dev]
    paths:
      - "BE/**"
      - ".github/workflows/be-ci.yml"
  workflow_dispatch:

jobs:
  ci-check:
    runs-on: ubuntu-latest
    env:
      DB_URL: "mysql://dummy:dummy@localhost:3306/dummy"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: BE/package-lock.json

      - name: Install Dependencies
        working-directory: ./BE
        run: npm ci

      - name: Generate Prisma Client
        working-directory: ./BE
        run: npx prisma generate

      #   - name: Lint Check
      #     working-directory: ./BE
      #     run: npm run lint

      - name: Build Check
        working-directory: ./BE
        run: npm run build
