name: be-ci

on:
  pull_request:
    branches: [dev]
    paths:
      - "BE/**"
      - ".github/workflows/be-ci.yml"
  workflow_dispatch:

jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: BE/package-lock.json

      - name: Install Dependencies
        working-directory: ./BE
        run: npm ci

      #   - name: Lint Check
      #     working-directory: ./BE
      #     run: npm run lint

      # NestJS 빌드 테스트
      - name: Build Check
        working-directory: ./BE
        run: npm run build
