name: CI - Build & Push Images

on:
  push:
    branches: ["main", "dev", "chore/121-cicd"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  FE_IMAGE_NAME: boostus-fe
  BE_IMAGE_NAME: boostus-be

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Buildx 세팅
        uses: docker/setup-buildx-action@v3

      - name: GHCR 로그인
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          # 이후에 팀 PAT 발급받으면 github.actor 로 수정해야 함
          username: limsr12
          password: ${{ secrets.GITHUB_TOKEN }}

      # FE
      - name: Build & Push FE
        uses: docker/build-push-action@v6
        with:
          context: ./FE
          file: ./FE/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.FE_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.FE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # BE
      - name: Build & Push BE
        uses: docker/build-push-action@v6
        with:
          context: ./BE
          file: ./BE/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BE_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            DB_URL=${{ secrets.DB_URL }}
