name: CD - Compose

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/compose-cd.yml"
      - "docker-compose.prod.yml"
  workflow_dispatch:

jobs:
  cd-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy docker-compose.prod.yml
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "docker-compose.prod.yml"
          target: "${{ secrets.DEPLOY_DIR }}"
