name: crawler-ci

on:
  pull_request:
    branches: [dev]
    paths:
      - "Crawler/**"
      - ".github/workflows/crawler-ci.yml"
  workflow_dispatch:

jobs:
  ci-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: Crawler/package-lock.json

      - name: Install Dependencies
        working-directory: ./Crawler
        run: npm ci

      #   - name: Lint Check
      #     working-directory: ./Crawler
      #     run: npm run lint

      - name: Build Check
        working-directory: ./Crawler
        run: npm run build
